### ISSUE TITLE
Conflict with jQuery datePicker 

### ISSUE THREAD

**Issue by memorx** [running-coder/jquery-form-validation#15]
Hi, I am trying to validate a JQuery DatePicker, using the  data_validation = "[NOTEMPTY]", however when I click submit when an empty data, the validator doesn't recognize the empty field for the datePicker, it does for the other fields but not for this one, it happens to all of the DatePickers. Thank you

**Comment by running-coder** [comment]
I've updated http://www.runningcoder.org/jqueryvalidation/demo#form-signup_v2 and added a "birthday" field as an example for your situation. Notice I added an $.alterValidationRules to add a custom rule to validate the datepicker input field and that rule is added on the HTML <input> field

the regular DATE validation rule validates a different date format "YYYY-MM-DD" so you can either use that one and chante the datepicker format or create your own validation rule as mentionned above

Hope this helps

**Comment by memorx** [comment]
Thank you very much =)

**Comment by memorx** [comment]
Hmmm, something is interfering with the validation still in the DatePicker, I will look into that and try to find a solution

**Comment by running-coder** [comment]
Let me know if you have an online demo I could look at or perhaps it's a version issue.

**Comment by memorx** [comment]
In is interesting, because when I am focus out, the validation works on the DatePicker, however when a submit the form it only alerts me the normal input fields. Sadly, I don't have a demo online, unless you would like to have a private conversation and I can show you sharing my computer =).

This is the code I have for my JQuery Date Picker
<input class="one-third-date-field datepicker hasDatepicker error" data-val="true" data-val-date="The field Construction Start Date must be a date." data-val-required="The Construction Start Date field is required." data-validation="[NOTEMPTY]" data-validation-message="Date must not be empty" id="TdlRelocationNonTraditional_v1_ConstructionStartDate" name="TdlRelocationNonTraditional_v1.ConstructionStartDate" type="text" value="1/1/0001 12:00:00 AM" readonly="readonly">

another example:

<input class="one-third-date-field datepicker opening-date hasDatepicker error" data-val="true" data-val-date="The field Opening Date must be a date." data-val-required="The Opening Date field is required." data-validation="[NOTEMPTY]" data-validation-message="Date must not be empty" id="TdlRelocationNonTraditional_v1_OpeningDate" name="TdlRelocationNonTraditional_v1.OpeningDate" type="text" value="1/1/0001 12:00:00 AM" readonly="readonly">

and this is the my Javascript

$.validate({
        submit: {
            settings: {
                form: '#NOR-check',
                inputContainer: '.field',
                errorListClass: 'ui red pointing below label'
            }
        },
        dynamic: {
            settings: {
                trigger: 'focusout'
            },
            callback: {
                onSuccess: function (node, input, keyCode) {
                    if ($(input).val()) {
                        $(input).parent().find('.ui.corner.label').removeClass('red').addClass('green');
                    }
                },
                onError: function (node, input, keyCode, error) {
                    $(input).parent().find('.ui.corner.label').removeClass('green');
                }
            }
        }
    });

    /**
    * private
    * Default options
    */
    var _options = {
        submit: {
            settings: {
                form: null,
                display: "inline",
                insertion: "append",
                allErrors: false,
                trigger: "click",
                button: "input[type='submit']",
                errorClass: "error",
                errorListClass: "error-list",
                inputContainer: null,
                clear: "focusin",
                scrollToError: false
            },
            callback: {
                onInit: null,
                onError: null,
                onBeforeSubmit: null,
                onSubmit: null,
                onAfterSubmit: null
            }
        },
        dynamic: {
            settings: {
                trigger: null,
                delay: 300
            },
            callback: {
                onSuccess: null,
                onError: null,
                onComplete: null
            }
        },
        debug: false
    };

  
![untitled](https://cloud.githubusercontent.com/assets/1566560/6659686/1d79f3a8-cb48-11e4-9d23-1b95fc6671a2.png)

**Comment by running-coder** [comment]
oh, the issue is the readonly attribute on the input field... the validation skips disabled and readonly because the value cannot be altered try to remove "readonly" from jquery.validation.js on line 472 and let me know if it works. I might remove that to only leave disabled...

**Comment by memorx** [comment]
That would be nice, pleaselet me know when you do, I removed the read only attribute ah yes it is working =). Thank you.

**Comment by memorx** [comment]
I am sorry to bother you again, that is the correct regex for this date Mar-03-1986?
so far I have: regex: /^\[A-Z][a-z][a-z]\-\d{2}\-\d{4}$/, The first 3 letter are not working =(. Thank you.

**Comment by running-coder** [comment]
I've tried these 2 regexes in the browser console, seems to work fine.

![date regex](http://i.imgur.com/2iW5iE8.png)

**Comment by running-coder** [comment]
I've removed the readonly attribute exception in the master branch
