### ISSUE TITLE
How to do a confirmation on submit?

### ISSUE THREAD

**Issue by vittore** [running-coder/jquery-form-validation#18]
I'm trying to make a simple validation with a Yes/No submit.
This is my code: https://jsfiddle.net/vxv54qca/1/

If I show/hide submit button when call form.submit() I get erro:

"Uncaught TypeError: myNode[0].submit is not a function"

May you help me?
v.

**Comment by mpavey0** [comment]
I assume you've moved on from this by now but in case it helps anyone else, the issue here may be the name of the Submit button being `submit`:
http://stackoverflow.com/questions/833032/submit-is-not-a-function-error-in-javascript

**Comment by running-coder** [comment]
Hey, indeed I've moved aside the project but I have the plan to rewrite it es6 in the coming weeks. I'm open to PR if you feel like you found the issue and it would still be compatible with the rest of the code.

Thx

**Comment by mpavey0** [comment]
Hi @running-coder — that's great! I just implemented the current version and (while I could suggest a few possible enhancements if you're interested) it works great — so thanks!

I was responding to @vittore , and I think the issue he faced was a problem with his code rather than your plugin.

**Comment by running-coder** [comment]
Regarding code enhancements, perhaps you can wait after the rewrite because everything will change anyway. For any bug fixes feel free to submit a PR :) ty
