### ISSUE TITLE
This is actually not an issue, but a comment!

### ISSUE THREAD

**Issue by swamyuma** [running-coder/jquery-form-validation#20]
I am new to github, I could not find a place to post just comments! This is in appreciation of the  [runningcoder](http://www.runningcoder.org/jquerytypeahead/documentation/) flowcharts section. It is awesome and I would like to ask the author about which graphing tool was used for making these.

**Comment by running-coder** [comment]
hey swamyuma, 

it's a chrome extension called gliffy. You can get it for free here: https://chrome.google.com/webstore/detail/gliffy-diagrams/bhmicilclplefnflapjmnngmkkkkpfad?hl=en

Enjoy.

**Comment by swamyuma** [comment]
Thanks, I am trying it now :+1:
