### ISSUE TITLE
Is there a way to autogrow field size when the selection string is really long?

### ISSUE THREAD

**Issue by swamyuma** [running-coder/jquery-form-validation#24]
I have a really long string returned from an ajax call. Is there a way to autogrow the field?  I tried using the [autogrow input](https://github.com/Pixabay/jQuery-autoGrowInput), but this does not work for an ajax data.

**Comment by running-coder** [comment]
hey swamyuma,

is this for the typeahead or the form-validation project? Also can you provide a code snippet of that you have tried so it might help me to understand the issue.

One thing you can try is to use the `onClick` callback and evaluate the `item[key].length` and expand your input based on the result, ex:

``` javascript
...
callback: {
    onClick: function (node, a, item, event) {
        if (item.display.length >= 10) {
            node.css({"width": "250px"})
        }
    }
}
```

**Comment by swamyuma** [comment]
Sorry for posting this in `form-validation`, I meant to post it in `typhead`!   Wow, that is so similar  to what I tried

```js
        ...
        callback: {
          onClickAfter: function(node, a, item, event) {
          $(this).autoGrowInput({minWidth: 100, maxWidth: 800, comfortZone: 90});
          console.log(item.ProductCatalogue, item.ItemNumber);
        }
     }
```

where `this` is `#id_item` in a `foreach` loop. I tried your suggestion too, but I think it is constrained by the fact that the row has multiple fields! Thanks so much for an awesome plugin :+1: !

**Comment by running-coder** [comment]
you are welcome!
