### ISSUE TITLE
How to Use Regex

### ISSUE THREAD

**Issue by solevy** [running-coder/jquery-form-validation#4]
Could you supply an example for a field working with regex? I have tried your demo Signing v4, and even that does not work properly (even on your site). Can you please advise?

**Comment by ayyaNaga** [comment]
Hi 
I am using URL Regex in my code
While validate the form empty filed
![screen shot 2015-02-06 at 2 31 14 pm](https://cloud.githubusercontent.com/assets/9268258/6076715/09400812-ae0d-11e4-804c-cba2fe728d63.png)
![screen shot 2015-02-06 at 2 31 32 pm](https://cloud.githubusercontent.com/assets/9268258/6076714/09276e1a-ae0d-11e4-95b8-cd59b72aea6d.png)



 is working fine but I Given the Correct web address "http://www.google.com" it will throw the error once again given the wrong Web address ""htsdftp://www.google.com"" This will accept so how to solve the problem.

data-validation="[NOTEMPTY]" 
data-validation-message="Link cannot be empty" 
data-validation-regex="/^(https?:\/\/)?((([a-z0-9]-*)*[a-z0-9]+\.?)*([a-z0-9]+))(\/[\w?=\.-]*)*$/"
data-validation-regex-message="Enter a valid Web Address"

**Comment by running-coder** [comment]
Fixed in 1.5.0
