### ISSUE TITLE
Conflict with cms ajax

### ISSUE THREAD

**Issue by Tuning-Soft** [running-coder/jquery-form-validation#6]
Hello! Help me please.
If i set form button id
![06-11-2014-01 06 45](https://cloud.githubusercontent.com/assets/1108013/4923955/eac0ef82-651e-11e4-9d48-904971287501.png)

in my site does't work ajax after i click Submit button
![06-11-2014-01 08 48](https://cloud.githubusercontent.com/assets/1108013/4923990/3512b9b2-651f-11e4-9b26-08838cab870d.png)

if i comment button id
![06-11-2014-01 09 49](https://cloud.githubusercontent.com/assets/1108013/4924017/5f0691da-651f-11e4-976a-0b125ba9e1f0.png)

ajax work fine!)
![06-11-2014-01 11 04](https://cloud.githubusercontent.com/assets/1108013/4924051/b03865ec-651f-11e4-8b8c-6542ed36308b.png)

may be it's some trigger or event, but, how do I get around this?

Thank you for the plugin, it's great work!!

**Comment by running-coder** [comment]
Hey sorry if took long to reply, are you still having this issue with the latest version?

**Comment by Tuning-Soft** [comment]
Helllo!!!
This was the case for me, i comment code in plugin:
```
//node.on("submit", false);
//e.preventDefault();
//options.submit.callback.onSubmit ? _executeCallback(options.submit.callback.onSubmit, [node]) : submitForm();
//return false
ну и еще кое-что переделал под себя, чувтсвую себя как в танке!)
```
http://tuning-soft.ru/1c-bitrix/modules/demo/api.formdesigner/

**Comment by running-coder** [comment]
Oh!.. Yea so the form validation removes any binding you have previously done on the form submission or the input submit click. You need to bind your for submit inside the callback:

```javascript
typeof $.typeahead === 'function' && $.typeahead({
    ...
    callback: {
        onSubmit: function (node) {
           // Do your ajax call here
        }
    }
})
```

let me know if that helps
